/**
 * SINGLE SOURCE OF TRUTH for every fact and line of copy on the site.
 *
 * Rules for agents:
 *  - Read from here. Do not hardcode names, dates, numbers or links in components.
 *  - Do NOT edit this file. If something you need is missing, leave a
 *    `// CONTENT REQUEST: ...` comment in your component and report it in your
 *    final summary. The orchestrator owns this file.
 *  - Facts were verified against LinkedIn, the CV and public GitHub repos on
 *    2026-09-17. Nothing here is invented. Placeholders are marked TODO and must
 *    be rendered gracefully (i.e. hidden) if still empty.
 */

export const person = {
  name: 'Jorge Rodríguez Ruigómez',
  shortName: 'Jorge Rodríguez',
  firstName: 'Jorge',
  /** One line under the name in the hero. */
  headline: 'I turn AI capabilities into software people actually use.',
  /** Role line, mono, under the headline. */
  roleLine: 'Applied AI · Forward Deployed Engineering',
  /** Where / what now. */
  nowLine: 'M.S. Information Technology & Management, Illinois Tech · Chicago, IL',
  /** Availability chip in hero. Default assumption; confirm with Jorge. */
  availability: 'Seeking Summer 2027 internships · Full-time from May 2027',
  intro:
    'Telecommunications engineer turned applied AI builder. I have shipped multimodal RAG in research, generative AI document automation in banking and two products with real users. I own problems end to end: understand the workflow, design the data and AI pipeline, ship the interface, iterate on measured outcomes.',
  location: 'Chicago, IL',
  email: 'jorgerod.ruigomez@gmail.com',
  /** Phone is intentionally NOT rendered on the page. It lives only in the vCard and the PDF. */
  links: {
    linkedin: 'https://www.linkedin.com/in/jorge-r-ruigomez/',
    github: 'https://github.com/JorgeRguezz',
    resumePdf: '/Jorge_Rodriguez_Ruigomez_Resume.pdf',
    vcard: '/jorge-rodriguez-ruigomez.vcf',
  },
} as const

/** "At a glance" tiles. `value` is what count-up animates to; `display` is the final rendering. */
export const glance = [
  {
    value: 2,
    display: '2',
    label: 'hackathon podiums',
    detail: 'Winner, IndesIAHack · 2nd, Gaia-X Hub Spain',
  },
  {
    value: 10,
    display: '10/10',
    label: 'thesis grade',
    detail: 'Intelligent routing for generative AI · honors nomination',
  },
  {
    value: 2,
    display: '2',
    label: 'products shipped to real users',
    detail: 'ETSIT-UPM Alumni Network · World Cup 2026 league',
  },
  {
    value: 100,
    display: '100+',
    label: 'attendees',
    detail: 'Founder & investor talks I co-organized at TelecoEmprende',
  },
] as const

export type PipelineStep = {
  /** Short mono label, ≤ 3 words. */
  label: string
  /** One clause, ≤ 12 words. */
  detail: string
}

export type Project = {
  id: string
  /** Display name. */
  name: string
  /** One-line hook, ≤ 14 words. */
  hook: string
  /** Mono context line: what kind of project, when. */
  context: string
  /** The Input → System → Output story. Keep each string tight. */
  input: PipelineStep
  system: PipelineStep[]
  output: PipelineStep
  /** Why it matters / what it proves, 1–2 sentences. */
  outcome: string
  /** Headline metric to show large, if any. */
  metric?: { value: string; label: string }
  stack: string[]
  links: { label: string; href: string }[]
}

export const featuredProjects: Project[] = [
  {
    id: 'lol-rag',
    name: 'Multimodal LoL-RAG',
    hook: 'Turns hours of gameplay video into a system that answers questions with evidence.',
    context: 'Applied research · UPM GATV · 2026',
    input: {
      label: 'Raw video',
      detail: 'Hours of League of Legends gameplay: pixels, HUD, audio.',
    },
    system: [
      { label: 'Segment & sample', detail: 'Temporal segmentation and frame sampling.' },
      { label: 'Extract', detail: 'ASR transcripts, VLM frame descriptions, champion matching.' },
      { label: 'Sanitize', detail: 'Two-stage cleaning: strip contamination, normalize entities, quarantine.' },
      { label: 'Build knowledge', detail: 'Vector index plus chunk-entity knowledge graph.' },
      { label: 'Retrieve & answer', detail: 'Intent-aware hybrid retrieval, reranking, grounded generation.' },
    ],
    output: {
      label: 'Grounded answers',
      detail: 'FastAPI service and Next.js chat UI, Docker GPU deploy, offline eval.',
    },
    outcome:
      'Inference reads only sanitized artifacts, so every answer traces to validated evidence. Evaluated offline with ROUGE, BERTScore and RAGAS.',
    stack: ['Python', 'PyTorch', 'VLMs', 'Whisper ASR', 'Knowledge graphs', 'FastAPI', 'Next.js', 'Docker'],
    links: [
      { label: 'Code', href: 'https://github.com/JorgeRguezz/Multimodal-LoL-RAG' },
      { label: 'Agent workspace', href: 'https://github.com/JorgeRguezz/Multimodal-video-analysis-agent' },
    ],
  },
  {
    id: 'llm-router',
    name: 'Intelligent LLM Router',
    hook: 'Sends each prompt to the cheapest model that can answer it well.',
    context: 'B.Eng. thesis · UPM · 2025 · graded 10/10',
    input: {
      label: 'Every prompt',
      detail: 'All requests hitting the same large, expensive model.',
    },
    system: [
      { label: 'Benchmark', detail: 'Six LLMs on MMLU-Pro, including paraphrase robustness.' },
      { label: 'Measure', detail: 'Accuracy, cost per token and energy consumption per model.' },
      { label: 'Classify', detail: 'Fine-tuned BERT classifies each prompt by category.' },
      { label: 'Route', detail: 'Pick the cheapest model that meets the accuracy bar.' },
    ],
    output: {
      label: 'Right-sized answers',
      detail: 'Router plus chat UI (React front end, Python API).',
    },
    outcome:
      'Compared GPT-4.1 nano, GPT-4o mini, Llama 3.1 8B, Mistral 7B, Gemma 2 9B and Phi-4 head to head. Nominated for an honors distinction.',
    // TODO(Jorge): headline metric, e.g. { value: '−X%', label: 'cost at −Y pt accuracy' }
    metric: undefined,
    stack: ['Python', 'PyTorch', 'BERT', 'MMLU-Pro', 'OpenAI API', 'Hugging Face', 'React'],
    links: [{ label: 'Code', href: 'https://github.com/JorgeRguezz/TFG-limpio' }],
  },
  {
    id: 'worldcup',
    name: 'World Cup 2026 Prediction League',
    hook: 'A private prediction league that runs the real FIFA 2026 rulebook.',
    context: 'Side product · shipped Jun 2026 · ran the whole tournament',
    input: {
      label: 'Official rules',
      detail: 'FIFA 2026 regulations, fixtures and admin-entered results.',
    },
    system: [
      { label: 'Spec first', detail: 'PRD, rules-engine spec and phased implementation plan.' },
      { label: 'Rules engine', detail: '12 groups, 8 best thirds via FIFA’s 495-combination table.' },
      { label: 'Bracket', detail: 'Propagates matches M73–M104 exactly as FIFA numbers them.' },
      { label: 'Lock & score', detail: 'Predictions lock at kickoff; ranking recomputed on every result.' },
    ],
    output: {
      label: 'Live product',
      detail: 'Used by a group of friends on every match day of the tournament; admin panel included.',
    },
    outcome:
      'Built from PRD to PostgreSQL row-level security, with a tested rules engine. Proof that I can take an idea to a maintained product.',
    stack: ['React', 'Vite', 'TypeScript', 'Supabase', 'PostgreSQL', 'PL/pgSQL', 'Vercel'],
    links: [
      { label: 'Live app', href: 'https://worldcup-app-ten.vercel.app' },
      { label: 'Code', href: 'https://github.com/JorgeRguezz/worldcup_App' },
    ],
  },
]

export const otherProjects = [
  {
    name: 'ETSIT-UPM Alumni Network',
    detail: 'Registration, QR membership credentials, payments and event access. Launched July 2026 with a five-person team.',
    href: undefined,
  },
  {
    name: 'Tennis match analytics',
    detail: 'Match statistics from object detection on match video. First computer-vision project.',
    href: 'https://github.com/JorgeRguezz/ComputerVisionTennisProject',
  },
  {
    name: 'CareNest',
    detail: 'Harvard HSIL hackathon team project in Python.',
    href: 'https://github.com/kayser17/HSIL-Harvard-Hackathon-CareNest',
  },
  {
    name: 'IdC · ISST project',
    detail: 'Fourth-year TypeScript course project, Telecommunications Engineering.',
    href: 'https://github.com/JorgeRguezz/IdC-Project-ISST',
  },
] as const

export type ExperienceItem = {
  role: string
  org: string
  orgDetail?: string
  location: string
  start: string
  end: string
  bullets: string[]
  tags?: string[]
}

export const experience: ExperienceItem[] = [
  {
    role: 'AI Research Assistant',
    org: 'Universidad Politécnica de Madrid',
    orgDetail: 'GATV research group · MOTIVATE-XR project',
    location: 'Madrid, Spain',
    start: 'Oct 2025',
    end: 'Aug 2026',
    bullets: [
      'Built an end-to-end multimodal AI system that turns video into searchable knowledge for grounded question answering.',
      'Designed and evaluated RAG pipelines combining vector databases, knowledge graphs and intent-aware hybrid retrieval.',
      'Enabled multi-step agent reasoning through MCP-based tools; containerized everything with Docker for reproducible experiments.',
    ],
    tags: ['VLMs', 'ASR', 'RAG', 'Knowledge graphs', 'MCP', 'Docker'],
  },
  {
    role: 'AI Engineer Intern',
    org: 'NTT DATA',
    orgDetail: 'Client: Banco Sabadell',
    location: 'Madrid, Spain',
    start: 'Feb 2025',
    end: 'Jul 2025',
    bullets: [
      'Helped ship production document automation for banking workflows (inheritance deeds, tax settlements) with generative AI and Intelligent Document Processing.',
      'Iterated LLM prompts for structured extraction; built Python preprocessing and output-validation functions for downstream workflows.',
    ],
    tags: ['LLMs', 'IDP', 'Prompt engineering', 'Python'],
  },
  {
    role: 'Founding Team Member',
    org: 'ETSIT-UPM Alumni Network',
    location: 'Remote',
    start: 'Oct 2025',
    end: 'Present',
    bullets: [
      'Designed, built and launched the school’s alumni platform (July 2026) in a five-person team, working directly with school leadership.',
      'Built registration, QR membership credentials, admin validation and event-access flows; integrated payment and QR-generation APIs.',
    ],
    tags: ['Product', 'APIs', 'Payments'],
  },
  {
    role: 'Vice President → Board Member',
    org: 'TelecoEmprende',
    orgDetail: 'ETSIT-UPM entrepreneurship club',
    location: 'Madrid, Spain',
    start: 'Oct 2025',
    end: 'Present',
    bullets: [
      'Helped relaunch the club and grow it to 80 active members.',
      'Co-organized TelecoBuilders: three sessions with founders, executives and investors (Cabify CTO, TaxDown co-founders, JME Ventures CEO), 100+ attendees.',
    ],
    tags: ['Community', 'Leadership'],
  },
]

export const awards = [
  {
    title: 'Repsol Challenge Winner',
    event: 'IndesIAHack 2024',
    date: 'Nov 2024',
    detail:
      'AI-powered energy-transition assistant: chatbot, EV and solar savings calculator, automated social content.',
  },
  {
    title: '2nd Place',
    event: 'Gaia-X Hub Spain Hackathon',
    date: 'Dec 2024',
    detail:
      'Data-space ETL pipeline, ML scoring model and UI to assess housing locations and investment opportunities.',
  },
] as const

export const education = [
  {
    school: 'Illinois Institute of Technology',
    degree: 'M.S. Information Technology & Management',
    focus: 'Applied Data Science & AI',
    start: 'Aug 2026',
    end: 'May 2027',
    location: 'Chicago, IL',
    notes: ['UPM International Mobility Scholarship', 'Santander Non-Erasmus Scholarship'],
  },
  {
    school: 'Universidad Politécnica de Madrid',
    degree: 'Master’s in Telecommunications Engineering',
    focus: 'Machine Learning & Data Science',
    start: 'Sep 2025',
    end: 'May 2027',
    location: 'Madrid, Spain',
    notes: [],
  },
  {
    school: 'Universidad Politécnica de Madrid',
    degree: 'B.Eng. Telecommunication Technologies & Services',
    focus: undefined,
    start: 'Sep 2020',
    end: 'Jun 2025',
    location: 'Madrid, Spain',
    notes: ['Thesis: Intelligent routing for generative AI models · 10/10, honors nomination'],
  },
] as const

export const skills = [
  {
    group: 'Applied AI',
    items: ['LLMs', 'AI agents', 'RAG', 'Multimodal AI', 'MCP', 'Knowledge graphs', 'Prompt engineering', 'IDP', 'Evaluation'],
  },
  {
    group: 'Engineering',
    items: ['API design & integration', 'Docker', 'Kubernetes', 'Azure AI', 'Git', 'Data validation', 'Supabase / PostgreSQL'],
  },
  {
    group: 'Languages & data',
    items: ['Python', 'TypeScript', 'JavaScript', 'SQL', 'Java', 'C', 'PyTorch', 'Pandas', 'NumPy'],
  },
  {
    group: 'Human languages',
    items: ['Spanish (native)', 'English (C1 · TOEFL iBT 104)'],
  },
] as const

export const beyond = {
  title: 'Beyond the keyboard',
  items: [
    {
      label: 'Summer Engineer · WindAid Institute',
      when: 'Aug – Sep 2024 · Trujillo, Peru',
      detail: 'Designed, built and installed wind turbines in developing residential areas.',
    },
  ],
} as const

export const contact = {
  title: 'Let’s talk.',
  lead: 'Save my contact and reach out whenever suits you. Email is the fastest way to reach me.',
  saveLabel: 'Save my contact',
  resumeLabel: 'Resume (PDF)',
} as const

export const footer = {
  line: 'Built in a day with React, Tailwind and Motion. Deployed on Vercel.',
  sourceHref: 'https://github.com/JorgeRguezz/MyPortfolio',
} as const

/** Section order and labels used for eyebrows and the pipeline gutter nodes. */
export const sections = [
  { id: 'glance', index: '01', label: 'At a glance' },
  { id: 'work', index: '02', label: 'Featured work' },
  { id: 'experience', index: '03', label: 'Experience' },
  { id: 'awards', index: '04', label: 'Awards' },
  { id: 'education', index: '05', label: 'Education' },
  { id: 'skills', index: '06', label: 'Skills' },
  { id: 'beyond', index: '07', label: 'Beyond' },
  { id: 'contact', index: '08', label: 'Contact' },
] as const

export type SectionId = (typeof sections)[number]['id']
